version: "3.5"
services:
    react-admin:
        image: eu.gcr.io/vivid-planet-public/dev/node-10-dev:master
        user: "${RUN_AS_UID}:0"
        volumes:
            - ./:/opt/app-root/src
        command: bash -c "touch .starting && yarn install && yarn run build && rm .starting && yarn run start"
    react-admin-storybook:
        image: eu.gcr.io/vivid-planet-public/dev/node-10-dev:master
        user: "${RUN_AS_UID}:0"
        volumes:
            - ./:/opt/app-root/src
        ports:
            - 8080:8080
        command: bash -c "./wait-while-starting.sh && cd packages/react-admin-stories && yarn start-storybook --port=8080"
        depends_on:
            - react-admin
    githook:
        image: "eu.gcr.io/vivid-planet-public/dev/githook-lint-installer:master"
        volumes:
            - ./:/tmp
